apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zbot-relay.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "zbot-relay.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "zbot-relay.name" . }}
    spec:
      containers:
        - name: zbot-relay
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
