replicaCount: 1

image:
  repository: panostaikun/zbot-relay
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
